int a = 4;
int b = 6;
int c = 8;
int d = 3;
int e = 2;
int max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.Write("максимальное число ");
Console.WriteLine(max);
